import type { Scene } from "./scenes";

export interface CastImage extends Scene {
  gender: "female" | "male" | "nonbinary" | "unspecified";
  name: string;
  role: string;
  species: string;
}

export const castPeople: CastImage[] = [
  {
    alt: "Generated portrait of Maya Solis",
    gender: "female",
    id: "maya-solis",
    kind: "photo",
    name: "Maya Solis",
    role: "Product designer",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/maya-solis.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Hana Park",
    gender: "female",
    id: "hana-park",
    kind: "photo",
    name: "Hana Park",
    role: "Researcher",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/hana-park.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Zara Ndiaye",
    gender: "female",
    id: "zara-ndiaye",
    kind: "photo",
    name: "Zara Ndiaye",
    role: "Marketing",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/zara-ndiaye.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Luca Moretti",
    gender: "male",
    id: "luca-moretti",
    kind: "photo",
    name: "Luca Moretti",
    role: "Support lead",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/luca-moretti.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Jun Park",
    gender: "male",
    id: "jun-park",
    kind: "photo",
    name: "Jun Park",
    role: "Data",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/jun-park.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Marcus Hale",
    gender: "male",
    id: "marcus-hale",
    kind: "photo",
    name: "Marcus Hale",
    role: "Founder",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/marcus-hale.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Meera Kapoor",
    gender: "female",
    id: "meera-kapoor",
    kind: "photo",
    name: "Meera Kapoor",
    role: "Counsel",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/meera-kapoor.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Niels Holm",
    gender: "male",
    id: "niels-holm",
    kind: "photo",
    name: "Niels Holm",
    role: "Advisor",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/niels-holm.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Leila Hassan",
    gender: "female",
    id: "leila-hassan",
    kind: "photo",
    name: "Leila Hassan",
    role: "Researcher",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/leila-hassan.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Diego Ramos",
    gender: "male",
    id: "diego-ramos",
    kind: "photo",
    name: "Diego Ramos",
    role: "Intern",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/diego-ramos.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of In\u00e8s Moreau",
    gender: "female",
    id: "ines-moreau",
    kind: "photo",
    name: "In\u00e8s Moreau",
    role: "Ops",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/ines-moreau.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Arjun Mehta",
    gender: "male",
    id: "arjun-mehta",
    kind: "photo",
    name: "Arjun Mehta",
    role: "PM",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/arjun-mehta.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Camila Duarte",
    gender: "female",
    id: "camila-duarte",
    kind: "photo",
    name: "Camila Duarte",
    role: "Marketing",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/camila-duarte.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Sasha Kim",
    gender: "nonbinary",
    id: "sasha-kim",
    kind: "photo",
    name: "Sasha Kim",
    role: "Staff engineer",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/sasha-kim.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Freya Lund",
    gender: "female",
    id: "freya-lund",
    kind: "photo",
    name: "Freya Lund",
    role: "Product designer",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/freya-lund.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Saoirse Flynn",
    gender: "female",
    id: "saoirse-flynn",
    kind: "photo",
    name: "Saoirse Flynn",
    role: "Marketing",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/saoirse-flynn.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Rowan O'Brien",
    gender: "male",
    id: "rowan-obrien",
    kind: "photo",
    name: "Rowan O'Brien",
    role: "Support lead",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/rowan-obrien.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Erik Lindqvist",
    gender: "male",
    id: "erik-lindqvist",
    kind: "photo",
    name: "Erik Lindqvist",
    role: "Sales",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/erik-lindqvist.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Chloe Bennett",
    gender: "female",
    id: "chloe-bennett",
    kind: "photo",
    name: "Chloe Bennett",
    role: "Intern",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/chloe-bennett.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Isla Reid",
    gender: "female",
    id: "isla-reid",
    kind: "photo",
    name: "Isla Reid",
    role: "Ops",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/isla-reid.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Lars Bergman",
    gender: "male",
    id: "lars-bergman",
    kind: "photo",
    name: "Lars Bergman",
    role: "Data",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/lars-bergman.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Morgan Reed",
    gender: "nonbinary",
    id: "morgan-reed",
    kind: "photo",
    name: "Morgan Reed",
    role: "Researcher",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/morgan-reed.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Amina Osei",
    gender: "female",
    id: "amina-osei",
    kind: "photo",
    name: "Amina Osei",
    role: "Ops",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/amina-osei.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Malik Johnson",
    gender: "male",
    id: "malik-johnson",
    kind: "photo",
    name: "Malik Johnson",
    role: "PM",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/malik-johnson.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Yuki Tanaka",
    gender: "female",
    id: "yuki-tanaka",
    kind: "photo",
    name: "Yuki Tanaka",
    role: "Advisor",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/yuki-tanaka.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Helen Frost",
    gender: "female",
    id: "helen-frost",
    kind: "photo",
    name: "Helen Frost",
    role: "Counsel",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/helen-frost.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Bridget Cairns",
    gender: "female",
    id: "bridget-cairns",
    kind: "photo",
    name: "Bridget Cairns",
    role: "Founder",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/bridget-cairns.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Omar Khalil",
    gender: "male",
    id: "omar-khalil",
    kind: "photo",
    name: "Omar Khalil",
    role: "Sales",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/omar-khalil.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Sofia Reyes",
    gender: "female",
    id: "sofia-reyes",
    kind: "photo",
    name: "Sofia Reyes",
    role: "Marketing",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/sofia-reyes.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Kai Thompson",
    gender: "male",
    id: "kai-thompson",
    kind: "photo",
    name: "Kai Thompson",
    role: "Support lead",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/kai-thompson.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Ananya Sharma",
    gender: "female",
    id: "ananya-sharma",
    kind: "photo",
    name: "Ananya Sharma",
    role: "Intern",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/ananya-sharma.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Hiro Sato",
    gender: "male",
    id: "hiro-sato",
    kind: "photo",
    name: "Hiro Sato",
    role: "Advisor",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/hiro-sato.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Theo Miller",
    gender: "male",
    id: "theo-miller",
    kind: "photo",
    name: "Theo Miller",
    role: "Product designer",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/theo-miller.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Nia Brooks",
    gender: "female",
    id: "nia-brooks",
    kind: "photo",
    name: "Nia Brooks",
    role: "Marketing",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/nia-brooks.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Elise Carter",
    gender: "female",
    id: "elise-carter",
    kind: "photo",
    name: "Elise Carter",
    role: "PM",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/elise-carter.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Jordan Wells",
    gender: "nonbinary",
    id: "jordan-wells",
    kind: "photo",
    name: "Jordan Wells",
    role: "Staff engineer",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/jordan-wells.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Graham Price",
    gender: "male",
    id: "graham-price",
    kind: "photo",
    name: "Graham Price",
    role: "Counsel",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/graham-price.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Linh Nguyen",
    gender: "female",
    id: "linh-nguyen",
    kind: "photo",
    name: "Linh Nguyen",
    role: "Researcher",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/linh-nguyen.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Miguel Santos",
    gender: "male",
    id: "miguel-santos",
    kind: "photo",
    name: "Miguel Santos",
    role: "Intern",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/miguel-santos.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Amara Cole",
    gender: "female",
    id: "amara-cole",
    kind: "photo",
    name: "Amara Cole",
    role: "Product designer",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/amara-cole.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Ezra Cohen",
    gender: "male",
    id: "ezra-cohen",
    kind: "photo",
    name: "Ezra Cohen",
    role: "Founder",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/ezra-cohen.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Rosa M\u00e9ndez",
    gender: "female",
    id: "rosa-mendez",
    kind: "photo",
    name: "Rosa M\u00e9ndez",
    role: "Advisor",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/rosa-mendez.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Ren Okada",
    gender: "nonbinary",
    id: "ren-okada",
    kind: "photo",
    name: "Ren Okada",
    role: "Staff engineer",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/ren-okada.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Connor Hayes",
    gender: "male",
    id: "connor-hayes",
    kind: "photo",
    name: "Connor Hayes",
    role: "Sales",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/connor-hayes.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Fatima Rahman",
    gender: "female",
    id: "fatima-rahman",
    kind: "photo",
    name: "Fatima Rahman",
    role: "Researcher",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/fatima-rahman.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Derrick Hayes",
    gender: "male",
    id: "derrick-hayes",
    kind: "photo",
    name: "Derrick Hayes",
    role: "Support lead",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/derrick-hayes.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Nora Blake",
    gender: "female",
    id: "nora-blake",
    kind: "photo",
    name: "Nora Blake",
    role: "Ops",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/nora-blake.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Tasha Greene",
    gender: "female",
    id: "tasha-greene",
    kind: "photo",
    name: "Tasha Greene",
    role: "Marketing",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/tasha-greene.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Noah Petrov",
    gender: "male",
    id: "noah-petrov",
    kind: "photo",
    name: "Noah Petrov",
    role: "Intern",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/noah-petrov.webp",
    tone: "light",
  },
  {
    alt: "Generated portrait of Valeria Cruz",
    gender: "female",
    id: "valeria-cruz",
    kind: "photo",
    name: "Valeria Cruz",
    role: "PM",
    species: "human",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-people/valeria-cruz.webp",
    tone: "light",
  },
];

export const castAnimals: CastImage[] = [
  {
    alt: "Generated dog portrait: Maple",
    gender: "unspecified",
    id: "maple-golden",
    kind: "photo",
    name: "Maple",
    role: "Support mascot",
    species: "dog",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/maple-golden.webp",
    tone: "light",
  },
  {
    alt: "Generated dog portrait: Ink",
    gender: "unspecified",
    id: "ink-lab",
    kind: "photo",
    name: "Ink",
    role: "Ops buddy",
    species: "dog",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/ink-lab.webp",
    tone: "light",
  },
  {
    alt: "Generated dog portrait: Biscuit",
    gender: "unspecified",
    id: "biscuit-corgi",
    kind: "photo",
    name: "Biscuit",
    role: "Office pup",
    species: "dog",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/biscuit-corgi.webp",
    tone: "light",
  },
  {
    alt: "Generated cat portrait: Mango",
    gender: "unspecified",
    id: "mango-tabby",
    kind: "photo",
    name: "Mango",
    role: "Product cat",
    species: "cat",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/mango-tabby.webp",
    tone: "light",
  },
  {
    alt: "Generated cat portrait: Mist",
    gender: "unspecified",
    id: "mist-shorthair",
    kind: "photo",
    name: "Mist",
    role: "Design critter",
    species: "cat",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/mist-shorthair.webp",
    tone: "light",
  },
  {
    alt: "Generated cat portrait: Jack",
    gender: "unspecified",
    id: "tuxedo-jack",
    kind: "photo",
    name: "Jack",
    role: "Office cat",
    species: "cat",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/tuxedo-jack.webp",
    tone: "light",
  },
  {
    alt: "Generated horse portrait: Bay",
    gender: "unspecified",
    id: "bay-star",
    kind: "photo",
    name: "Bay",
    role: "Brand mare",
    species: "horse",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/bay-star.webp",
    tone: "light",
  },
  {
    alt: "Generated horse portrait: Cloud",
    gender: "unspecified",
    id: "cloud-mare",
    kind: "photo",
    name: "Cloud",
    role: "Pasture lead",
    species: "horse",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/cloud-mare.webp",
    tone: "light",
  },
  {
    alt: "Generated horse portrait: Onyx",
    gender: "unspecified",
    id: "onyx-stallion",
    kind: "photo",
    name: "Onyx",
    role: "Studio horse",
    species: "horse",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/onyx-stallion.webp",
    tone: "light",
  },
  {
    alt: "Generated chameleon portrait: Leaf",
    gender: "unspecified",
    id: "leaf-veiled",
    kind: "photo",
    name: "Leaf",
    role: "Garden scout",
    species: "chameleon",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/leaf-veiled.webp",
    tone: "light",
  },
  {
    alt: "Generated chameleon portrait: Reef",
    gender: "unspecified",
    id: "reef-panther",
    kind: "photo",
    name: "Reef",
    role: "Color QA",
    species: "chameleon",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/reef-panther.webp",
    tone: "light",
  },
  {
    alt: "Generated chameleon portrait: Sun",
    gender: "unspecified",
    id: "sun-chameleon",
    kind: "photo",
    name: "Sun",
    role: "Habitat mascot",
    species: "chameleon",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/sun-chameleon.webp",
    tone: "light",
  },
  {
    alt: "Generated fish portrait: Azure",
    gender: "unspecified",
    id: "azure-betta",
    kind: "photo",
    name: "Azure",
    role: "Aquarium lead",
    species: "fish",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/azure-betta.webp",
    tone: "light",
  },
  {
    alt: "Generated fish portrait: Coin",
    gender: "unspecified",
    id: "coin-goldfish",
    kind: "photo",
    name: "Coin",
    role: "Lucky fish",
    species: "fish",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/coin-goldfish.webp",
    tone: "light",
  },
  {
    alt: "Generated fish portrait: Flash",
    gender: "unspecified",
    id: "koi-flash",
    kind: "photo",
    name: "Flash",
    role: "Pond mascot",
    species: "fish",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/koi-flash.webp",
    tone: "light",
  },
  {
    alt: "Generated bird portrait: Rio",
    gender: "unspecified",
    id: "rio-macaw",
    kind: "photo",
    name: "Rio",
    role: "Community bird",
    species: "bird",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/rio-macaw.webp",
    tone: "light",
  },
  {
    alt: "Generated bird portrait: Pip",
    gender: "unspecified",
    id: "pip-canary",
    kind: "photo",
    name: "Pip",
    role: "Studio songbird",
    species: "bird",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/pip-canary.webp",
    tone: "light",
  },
  {
    alt: "Generated bird portrait: Luna",
    gender: "unspecified",
    id: "luna-barn",
    kind: "photo",
    name: "Luna",
    role: "Night docs",
    species: "bird",
    src: "https://ik.imagekit.io/16u211libb/smoothui/troupe-animals/luna-barn.webp",
    tone: "light",
  },
];
