// Plain data only — safe to import from route handlers (llms.txt, /r/[slug]).
// Adding a day = one entry here + one component file + one line in registry.tsx.

export type InteractionMeta = {
  slug: string;
  day: number;
  date: string; // ISO
  title: string;
  description: string;
  hint: string; // one-line "how to play" shown on the stage
  dependencies: string[];
  file: string; // path under src/interactions/
  assets?: string[]; // paths under public/ bundled by the registry endpoint
  tags: string[]; // interaction verbs shown in the day sidebar
};

export const interactionsMeta: InteractionMeta[] = [
  {
    slug: "elastic-slider",
    day: 1,
    date: "2026-08-18",
    title: "Elastic Slider",
    description:
      "An iOS-style slider that stretches past its ends and springs back, with a rising tick sound every 10 steps.",
    hint: "Drag it, then keep dragging past the end. Sound on.",
    dependencies: ["motion"],
    file: "elastic-slider.tsx",
    tags: ["Drag", "Spring", "Sound"],
  },
  {
    slug: "like-button",
    day: 2,
    date: "2026-08-19",
    title: "Like Button",
    description:
      "A heart that pops with a spring, a ring flash, a burst of particles, and a satisfying pop sound.",
    hint: "Tap the heart. Sound on.",
    dependencies: ["motion"],
    file: "like-button.tsx",
    tags: ["Tap", "Particles", "Sound"],
  },
  {
    slug: "infinite-icon-grid",
    day: 3,
    date: "2026-08-20",
    title: "Infinite Icon Grid",
    description:
      "A window onto an endless grid of icons. Drag in any direction forever; icons pop in at random moments once fully on screen and pop away at the edges, with soft inertia and a slow idle drift. Bring your own images via the icons prop.",
    hint: "Drag anywhere. It never ends.",
    dependencies: [],
    file: "icon-grid.tsx",
    tags: ["Drag", "Infinite", "Spring"],
  },
  {
    slug: "intelligence-glow",
    day: 4,
    date: "2026-08-21",
    title: "Apple Intelligence Glow",
    description:
      "The Apple Intelligence summon effect for React: a flowing multicolor glow that sweeps around the edge of the screen, blooms inward, and breathes while it listens — the Siri-style edge light. Tap to summon, tap again to dismiss.",
    hint: "Tap to summon. Sound on.",
    dependencies: [],
    file: "intelligence-glow.tsx",
    tags: ["Tap", "Glow", "Sound"],
  },
  {
    slug: "proximity-grid",
    day: 5,
    date: "2026-08-22",
    title: "Proximity Grid",
    description:
      "A block of dots that feels your cursor: inside the influence radius they bloom into rounded squares, brighten, and get magnetically pulled toward the pointer with a smooth eased falloff. Flip the magnet negative and the grid repels instead.",
    hint: "Move your cursor. The grid feels it.",
    dependencies: [],
    file: "proximity-grid.tsx",
    tags: ["Hover", "Magnet", "Spring"],
  },
  {
    slug: "shader-button",
    day: 6,
    date: "2026-08-24",
    title: "Shader Button",
    description:
      "A pill button with a thermal shader border: a heatmap ring of blue, gold, and red flows around the machined icon well. Hovering doubles the heat, shifts in a hot magenta, and blooms a halo; pressing compresses the button. Built on Paper Shaders.",
    hint: "Hover it. Press it.",
    dependencies: ["@paper-design/shaders-react"],
    file: "shader-button.tsx",
    tags: ["Hover", "Tap", "Glow"],
  },
  {
    slug: "vinyl-player",
    day: 7,
    date: "2026-08-25",
    title: "Vinyl Player",
    description:
      "A tactile record player for React: tap to bring the motor up to speed, watch the needle drop and follow the groove, then grab the vinyl to scratch it forwards or backwards with matching audio.",
    hint: "Tap to play. Grab the vinyl and scratch it.",
    dependencies: [],
    file: "vinyl-player.tsx",
    tags: ["Tap", "Drag", "Sound"],
  },
  {
    slug: "transform-flow",
    day: 8,
    date: "2026-08-26",
    title: "Transform Flow",
    description:
      "Six inputs cross a shared seam and emerge as their paired outputs. Hold anywhere to speed up the flow, wake the particle field, and build a full-screen bloom.",
    hint: "Hold anywhere to accelerate the handoff. Keep holding to charge the bloom.",
    dependencies: [],
    file: "transform-flow.tsx",
    tags: ["Hold", "Transform", "Sound"],
  },
  {
    slug: "balloon-numbers",
    day: 9,
    date: "2026-08-27",
    title: "Balloon Numbers",
    description:
      "Turn any number into a small bouquet of foil balloons. Each digit floats on a fixed-length tether, drifts in occasional gusts, softly collides with its neighbours, and gets out of the cursor’s way.",
    hint: "Move through the bouquet. Type any number in the tuner.",
    dependencies: [],
    file: "balloon-numbers.tsx",
    assets: Array.from({ length: 10 }, (_, digit) => `balloon-numbers/${digit}.svg`),
    tags: ["Hover", "Wind", "Spring"],
  },
  {
    slug: "text-lift",
    day: 10,
    date: "2026-08-28",
    title: "Text Lift",
    description:
      "A word that stays still until your cursor moves through it. Nearby letters lift, gain weight, narrow a little, then settle back onto one baseline.",
    hint: "Move through the word. The type follows your cursor.",
    dependencies: ["motion"],
    file: "text-lift.tsx",
    tags: ["Hover", "Spring"],
  },
  {
    slug: "wind-chimes",
    day: 11,
    date: "2026-09-08",
    title: "Wind Chimes",
    description:
      "A hanging chime set with coloured tubes that settle into a quiet drift, answer a cursor with an inner glow, and ring when you pull them through the air.",
    hint: "Drag a tube, then let the air take it.",
    dependencies: [],
    file: "wind-chimes.tsx",
    tags: ["Drag", "Wind", "Sound"],
  },
  {
    slug: "scratch-reveal",
    day: 12,
    date: "2026-09-08",
    title: "Scratch Reveal",
    description:
      "A real canvas scratch card for credits, offers, prizes, or any moment that deserves a little friction before the reveal.",
    hint: "Scratch the surface to uncover what is waiting.",
    dependencies: [],
    file: "scratch-reveal.tsx",
    tags: ["Drag", "Reveal", "Glow"],
  },
  {
    slug: "icon-cloud",
    day: 13,
    date: "2026-08-23",
    title: "Icon Cloud",
    description: "A draggable constellation of interface ideas orbiting in depth, with momentum, pause control, and a calmer reduced-motion state.",
    hint: "Drag the constellation. Let go and watch it coast.",
    dependencies: ["lucide-react"],
    file: "catch-up-interactions.tsx",
    tags: ["Drag", "Orbit", "Depth"],
  },
  {
    slug: "dia-reveal",
    day: 14,
    date: "2026-08-29",
    title: "Dia Reveal",
    description: "Oversized type revealed by a moving spectrum that rotates through a tiny manifesto without shifting the layout.",
    hint: "Stay for the next line.",
    dependencies: ["motion"],
    file: "catch-up-interactions.tsx",
    tags: ["Text", "Reveal", "Glow"],
  },
  {
    slug: "text-3d-flip",
    day: 15,
    date: "2026-08-30",
    title: "3D Type Flip",
    description: "A headline whose letters rotate through real perspective one after another when you challenge it.",
    hint: "Hover or tap the headline.",
    dependencies: ["motion"],
    file: "catch-up-interactions.tsx",
    tags: ["Hover", "Text", "Depth"],
  },
  {
    slug: "living-dropdown",
    day: 16,
    date: "2026-08-31",
    title: "Living Dropdown",
    description: "An accessible Radix menu with a shared highlight that glides between choices instead of blinking between states.",
    hint: "Open it, then move through the choices.",
    dependencies: ["motion", "radix-ui", "lucide-react"],
    file: "catch-up-interactions.tsx",
    tags: ["Tap", "Menu", "Spring"],
  },
  {
    slug: "led-board",
    day: 17,
    date: "2026-09-01",
    title: "LED Board",
    description: "A dot-matrix year plate that wakes row by row on hover while idle pixels flicker like imperfect hardware.",
    hint: "Hover the board to light every diode.",
    dependencies: [],
    file: "catch-up-interactions.tsx",
    tags: ["Hover", "Light", "Grid"],
  },
  {
    slug: "arcade-pixel",
    day: 18,
    date: "2026-09-02",
    title: "Arcade Pixel",
    description: "A phosphor-bright pixel marquee with scanlines, bloom, chromatic edges, and a message built for an imaginary arcade cabinet.",
    hint: "Watch the signal travel through the display.",
    dependencies: ["motion"],
    file: "catch-up-interactions.tsx",
    tags: ["Loop", "Text", "Glow"],
  },
  {
    slug: "precision-scrubber",
    day: 19,
    date: "2026-09-03",
    title: "Precision Scrubber",
    description: "A tactile intensity control with ticks, direct manipulation, keyboard support, and a value that stays attached to the gesture.",
    hint: "Drag across the rail or use the arrow keys.",
    dependencies: ["motion"],
    file: "catch-up-interactions.tsx",
    tags: ["Drag", "Control", "Spring"],
  },
  {
    slug: "morph-surface",
    day: 20,
    date: "2026-09-04",
    title: "Morph Surface",
    description: "A compact idea dock that unfolds into a focused note surface, submits, and resolves into a quiet success state.",
    hint: "Open it, leave tomorrow a note, then press Command–Enter.",
    dependencies: ["motion"],
    file: "catch-up-interactions.tsx",
    tags: ["Tap", "Morph", "Input"],
  },
  {
    slug: "future-comment",
    day: 21,
    date: "2026-09-05",
    title: "Future Comment",
    description: "A tiny avatar marker that expands into design feedback sent backward from your future self.",
    hint: "Tap the blue marker.",
    dependencies: ["motion"],
    file: "catch-up-interactions.tsx",
    tags: ["Tap", "Morph", "Message"],
  },
  {
    slug: "confidential-folder",
    day: 22,
    date: "2026-09-06",
    title: "Confidential Folder",
    description: "A sealed archival sleeve with a letter that rises, flips, and reveals a note about reclaiming unfinished days.",
    hint: "Open the archive and pull out the letter.",
    dependencies: ["motion"],
    file: "catch-up-interactions.tsx",
    tags: ["Tap", "Reveal", "Depth"],
  },
  {
    slug: "dynamic-grid-gallery",
    day: 23,
    date: "2026-09-07",
    title: "Dynamic Grid Gallery",
    description: "Six original generative posters share a grid whose rows and columns fluidly make room for your attention.",
    hint: "Move across the studies. Every neighbour yields.",
    dependencies: [],
    file: "catch-up-interactions.tsx",
    tags: ["Hover", "Grid", "Image"],
  },
  {
    slug: "prompt-box",
    day: 24,
    date: "2026-09-09",
    title: "Prompt Box",
    description: "A compact creative prompt that expands around intent and switches between Imagine, Polish, and Ship modes.",
    hint: "Open the composer, choose a mode, and type an idea.",
    dependencies: ["motion", "lucide-react"],
    file: "catch-up-interactions.tsx",
    tags: ["Tap", "Input", "Morph"],
  },
  {
    slug: "scan-idea",
    day: 25,
    date: "2026-09-10",
    title: "Scan Idea",
    description: "A paper sketch materializes, turns through a scanning beam, and files itself away for tomorrow.",
    hint: "Capture the idea.",
    dependencies: ["motion"],
    file: "catch-up-interactions.tsx",
    tags: ["Tap", "Scan", "Depth"],
  },
  {
    slug: "focus-sprint",
    day: 26,
    date: "2026-09-11",
    title: "Focus Sprint",
    description: "A compact timer that grows into a wheel picker, then becomes a live countdown with pause and clear states.",
    hint: "Set a minute count and begin the sprint.",
    dependencies: ["motion", "@ncdai/react-wheel-picker"],
    file: "catch-up-interactions.tsx",
    tags: ["Tap", "Timer", "Morph"],
  },
  {
    slug: "smooth-dropdown",
    day: 27,
    date: "2026-09-12",
    title: "Smooth Dropdown",
    description: "A single icon grows into a complete action menu while one spring-driven selection rail follows your intent.",
    hint: "Tap the dot menu and move through the day.",
    dependencies: ["motion", "react-use-measure"],
    file: "catch-up-interactions.tsx",
    tags: ["Tap", "Menu", "Morph"],
  },
  {
    slug: "stacked-outline",
    day: 28,
    date: "2026-09-13",
    title: "Stacked Outline",
    description: "A draggable word leaves a velocity-sensitive stack of outlined afterimages behind it, then settles cleanly.",
    hint: "Grab MOVE and throw it around.",
    dependencies: ["motion"],
    file: "catch-up-interactions.tsx",
    tags: ["Drag", "Text", "Velocity"],
  },
  {
    slug: "physical-theme-switch",
    day: 29,
    date: "2026-09-14",
    title: "Physical Theme Switch",
    description: "A miniature day-and-night machine with a recessed track, dotted grip, and a short physical snap.",
    hint: "Flip the tiny sky.",
    dependencies: [],
    file: "catch-up-interactions.tsx",
    tags: ["Tap", "Toggle", "Light"],
  },
  {
    slug: "wheel-carousel",
    day: 30,
    date: "2026-09-15",
    title: "Wheel Carousel",
    description: "Original motion studies travel around a curved wheel with drag momentum, image crossfades, and a precise active marker.",
    hint: "Drag the type wheel or scroll through the studies.",
    dependencies: ["motion", "lucide-react"],
    file: "catch-up-interactions.tsx",
    tags: ["Drag", "Wheel", "Image"],
  },
  {
    slug: "living-persona",
    day: 31,
    date: "2026-09-16",
    title: "Living Persona",
    description: "A WebGL persona shifts its internal motion language between idle, listening, thinking, speaking, and sleep.",
    hint: "Move it through each state.",
    dependencies: ["@rive-app/react-webgl2"],
    file: "catch-up-interactions.tsx",
    tags: ["Tap", "State", "Glow"],
  },
  {
    slug: "shimmer-thought",
    day: 32,
    date: "2026-09-17",
    title: "Shimmer Thought",
    description: "A broad light band continuously searches across a sentence about the overlooked motion inside waiting.",
    hint: "Let the light finish the thought.",
    dependencies: ["motion"],
    file: "catch-up-interactions.tsx",
    tags: ["Loop", "Text", "Light"],
  },
  {
    slug: "presence-orb",
    day: 33,
    date: "2026-09-29",
    title: "Presence Orb",
    description: "A living WebGL presence with four distinct glass materials, responsive states, spectral colourways, and a shader you can tune in real time.",
    hint: "Tap the orb to move from resting to listening to speaking.",
    dependencies: ["three"],
    file: "orb-scene.tsx",
    tags: ["Tap", "State", "Glow"],
  },
];

export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://1iad.com";
